title: jekyll-rtd-theme
lang: en
description: GitHub-flavored docs theme for Jekyll

theme: null

debug:
  compress: false
  dist: false
  extension: true

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - jekyll-rtd-theme.gemspec
